version: "3.9"  # Use the latest version

services:
  nextjs:
    build:
      context: ./files
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - django
    networks:
      - back-tier

  django:
    build:
      context: ./zaco-global/zaco
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=database-1
      - POSTGRES_USER=zaco
      - POSTGRES_PASSWORD=K6g88gG.r657
      - POSTGRES_HOST=database-1.cpcvoyspvsdn.ap-south-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    networks:
      - back-tier

  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=zaco
      - POSTGRES_USER=zaco
      - POSTGRES_PASSWORD=zaco
    networks:
      - back-tier

networks:
  back-tier: