# Generated by Django 4.2.4 on 2024-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_category_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog2/%Y/%m/%d/'),
        ),
    ]
